schema-version = 2
release-version = "5.3.3"
project-vendor = "Bottlerocket"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[vendor.piyush]
registry = "public.ecr.aws/s2v1a1q8"

[sdk]
name = "bottlerocket-sdk"
version = "0.72.0"
vendor = "piyush"
