schema-version = 2
release-version = "5.3.2"
project-vendor = "Bottlerocket"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[vendor.local]
registry = "localhost:5000"

[sdk]
name = "bottlerocket-sdk"
version = "0.72.0"
vendor = "local"
